### ISSUE TITLE
i can't install driver in jetson nano

### ISSUE THREAD

**Issue by tinker495** [BlueRiverTech/hil_sdk_linux_x86_64#1]
when "sudo ./setup_hil_sdk" for install. there is an error 
syntax error "(" unexpected
what can i do to solve this problem?

**Comment by polzounov** [comment]
Hi!

I'm not too sure what is happening here, would you mind pasting the entire error?
This would give me a bit more context on the error.

**Comment by tinker495** [comment]
@jetson-nano:~/hil_sdk_linux_x86_64$ sudo ./setup_hil_sdk 
./setup_hil_sdk: 1: ./setup_hil_sdk: Syntax error: "(" unexpected

here is entire error i have no idea with this

**Comment by polzounov** [comment]
Hi,
I talked to someone on the Quanser team (the HIL SDK is code from Quanser, we are just redistributing it), and they said that the HIL SDK is not currently supported on ARM64 processors. They mentioned that they have plans to support it in the near future.

Have you tried running the SDK on a desktop computer (either Intel or AMD-based processor)?

**Comment by tinker495** [comment]
I tried running SDK on a PC and it's worked very well. but i just want to try transfer my RL based pendulum control project. however HIL SDK is not support on nvidia jetson... hmm... OK. thanks for the answer! can you mention to me when they support nvidia jetson?

**Comment by polzounov** [comment]
Of course! Good to hear it is working on your PC. I will update this issue when Quanser updates their SDK with ARM support.
Closing this issue for now.

Cheers

**Comment by polzounov** [comment]
@TinkTheBoush it may now work with the new drivers from Quanser, the link is: https://github.com/quanser/hil_sdk_linux_pi_3

(This is for the raspberry pi 3 but it may work on the Jetson since it is also ARM based)
