### ISSUE TITLE
https://github.com/quanser/hil_sdk_linux_x86_64

### ISSUE THREAD

**Issue by hlacheray** [BlueRiverTech/hil_sdk_linux_x86_64#2]
Hi, 
FYI, this new page 
https://github.com/quanser/hil_sdk_linux_x86_64

contains the latest version and future updates for the Quanser HIL SDK for the x86-based 64-bit Linux operating system (e.g., Ubuntu).

Cheers!

**Comment by polzounov** [comment]
Great! I updated this repo to link the Quanser page.
Cheers!
